/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fiapfilmenac;

import java.awt.Color;
import java.awt.Image;
import java.io.File;
import java.util.Set;
import javax.swing.ImageIcon;
import javax.swing.JComboBox;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author nkyon
 */
public class Situacao extends javax.swing.JFrame {
    JRadioButton netflix2, youtube2, amazon2, resultado;
    JComboBox combocaixinha;
    int indexcombo;
    boolean socorro;
    String titulozao, sinopsezin;
    /**
     * Creates new form Situacao
     */
    public Situacao(JRadioButton netflix, JRadioButton Youtube, JRadioButton Amazon, int indexCombo, boolean mesalva, String titulozinho, String Sinopsezinha) {
        this.netflix2 = netflix;
        this.youtube2 = Youtube;
        this.amazon2 = Amazon;
        this.indexcombo = indexCombo;
        this.socorro = mesalva;
        this.titulozao = titulozinho;
        this.sinopsezin = Sinopsezinha;
        
        // lblComboCaixinha.setSelectedItem("aaaa");
        
          initComponents(); 
        Netflix2.setEnabled(false); 
        Youtube2.setEnabled(false);
        Amazon2.setEnabled(false);
        if (netflix2.isSelected()) {
            
            Netflix2.setSelected(true);
            Netflix2.setForeground(Color.black);
            resultado = Netflix2;
        }
        if (youtube2.isSelected()) {
            
            Youtube2.setSelected(true);
            Youtube2.setForeground(Color.black);
            resultado = Youtube2;
        }
        if (amazon2.isSelected()) {
            
            Amazon2.setSelected(true);
            Amazon2.setForeground(Color.black);
            resultado = Amazon2;
        }
        //lblComboCaixinha.setEnabled(false);
        lblComboCaixinha.setEditable(false);
        lblComboCaixinha.setForeground(Color.black);
        lblComboCaixinha.setOpaque(false);
        lblComboCaixinha.setSelectedIndex(indexcombo);
        OhMeuDeus2.setEnabled(false);
        OhMeuDeus2.setForeground(Color.black);
        OhMeuDeus2.setOpaque(false);
        OhMeuDeus2.setSelected(socorro);
        Sinopse2.setEnabled(false);
        Sinopse2.setOpaque(false);
        Sinopse2.setText(sinopsezin);
        ReceberTexto1Titulo.setEnabled(false);
        ReceberTexto1Titulo.setOpaque(false);
        ReceberTexto1Titulo.setText(titulozinho);
        
        String assistido;
        if (socorro == false) {
            assistido = "Não assistido";
            
        } else{
            assistido = "assistido";
        }
        
        System.out.println("Titúlo do Filme: " + titulozao + "\nSinopse: " + sinopsezin + "\nGênero: " + 
                lblComboCaixinha.getSelectedItem().toString() + "\nOnde assistir: " + resultado.getText() + "\nAssistido: " + assistido);

         
   
   
   
//        JPanel test = new JPanel();
//        test.add(new StarRater(5));
//        test.setBounds(200,200,200,200);
//        Rating.add(test);
        

    }
    public Situacao(){
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblFotoReceber = new javax.swing.JLabel();
        Netflix2 = new javax.swing.JRadioButton();
        Youtube2 = new javax.swing.JRadioButton();
        Amazon2 = new javax.swing.JRadioButton();
        lblComboCaixinha = new javax.swing.JComboBox<>();
        OhMeuDeus2 = new javax.swing.JCheckBox();
        ReceberTexto1Titulo = new javax.swing.JTextField();
        Sinopse2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Info do Filme");
        setPreferredSize(new java.awt.Dimension(974, 483));
        setResizable(false);

        Netflix2.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        Netflix2.setText("Netflix");
        Netflix2.setOpaque(false);
        Netflix2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Netflix2ActionPerformed(evt);
            }
        });

        Youtube2.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        Youtube2.setText("Youtube");
        Youtube2.setOpaque(false);

        Amazon2.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        Amazon2.setText("Amazon");
        Amazon2.setOpaque(false);

        lblComboCaixinha.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblComboCaixinha.setForeground(new java.awt.Color(0, 0, 0));
        lblComboCaixinha.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione o Genero", "Ação", "Terror", "Comédia", "Drama" }));
        lblComboCaixinha.setEnabled(false);

        OhMeuDeus2.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        OhMeuDeus2.setText("Assistido");

        ReceberTexto1Titulo.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        ReceberTexto1Titulo.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        ReceberTexto1Titulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReceberTexto1TituloActionPerformed(evt);
            }
        });

        Sinopse2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        Sinopse2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Sinopse2ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel1.setText("TÍTULO DO FILME:");

        jLabel4.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel4.setText("SINOPSE:");

        jLabel2.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel2.setText("QUAL CATEGORIA:");

        jLabel3.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel3.setText("PLATAFORMA DISPONÍVEL:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(lblFotoReceber, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(jLabel1)))
                                .addGap(37, 37, 37)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Sinopse2, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ReceberTexto1Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(36, 36, 36)
                                .addComponent(lblComboCaixinha, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Youtube2)
                                .addGap(206, 206, 206))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(Netflix2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Amazon2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(OhMeuDeus2)
                                .addGap(27, 27, 27))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblFotoReceber, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ReceberTexto1Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Sinopse2, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel1))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(lblComboCaixinha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13)
                        .addComponent(Youtube2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(Amazon2)
                            .addComponent(OhMeuDeus2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Netflix2)))
                .addGap(48, 48, 48))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Netflix2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Netflix2ActionPerformed
        if (netflix2.isSelected()) {
        Netflix2.setAction(null);
        }    
    }//GEN-LAST:event_Netflix2ActionPerformed

    private void ReceberTexto1TituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReceberTexto1TituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ReceberTexto1TituloActionPerformed

    private void Sinopse2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Sinopse2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Sinopse2ActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Situacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Situacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Situacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Situacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Situacao().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Amazon2;
    public javax.swing.JRadioButton Netflix2;
    private javax.swing.JCheckBox OhMeuDeus2;
    private javax.swing.JTextField ReceberTexto1Titulo;
    private javax.swing.JTextField Sinopse2;
    private javax.swing.JRadioButton Youtube2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JComboBox<String> lblComboCaixinha;
    private javax.swing.JLabel lblFotoReceber;
    // End of variables declaration//GEN-END:variables
    public void recebendo(String receber){
        //  lblFotoReceber.setText(receber);

            JOptionPane.showMessageDialog(null, receber);
 
            ImageIcon imIco = new ImageIcon(receber);

            Image imFit = imIco.getImage();
 
            Image imgFit = imFit.getScaledInstance(lblFotoReceber.getWidth(), lblFotoReceber.getHeight(), Image.SCALE_SMOOTH);
       
            lblFotoReceber.setIcon(new ImageIcon(imgFit));
//        JFileChooser fileChooser = new JFileChooser();
// 
//        FileNameExtensionFilter filter = new FileNameExtensionFilter("4 Extensions Supported", "jpg", "png", "jpeg", "gif");
// 
//        fileChooser.setFileFilter(filter);
// 
//        int selected = fileChooser.showOpenDialog(null);
// 
//        if (selected == JFileChooser.APPROVE_OPTION) {
// 
//            File file = fileChooser.getSelectedFile();
//
//            String getselectedImage = file.getAbsolutePath();
// 
// 
//            JOptionPane.showMessageDialog(null, getselectedImage);
// 
//            ImageIcon imIco = new ImageIcon(getselectedImage);
//
//            Image imFit = imIco.getImage();
// 
//            Image imgFit = imFit.getScaledInstance(lblFotoReceber.getWidth(), lblFotoReceber.getHeight(), Image.SCALE_SMOOTH);
// 
//            lblFotoReceber.setIcon(new ImageIcon(imgFit));
//        }
//    }

}
        public void recebeTexto(String aa1){
        ReceberTexto1Titulo.setText(aa1);
        }
        public void recebeTexto2(String aaaa){
        Sinopse2.setText(aaaa);
        }
}
